### ISSUE TITLE
[FEAT] 그룹 컴포넌트 생성

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/trti_frontend#11]
## 설명
- 메인 페이지에서 사용되는 그룹 컴포넌트 생성
![1](https://user-images.githubusercontent.com/28842641/146725908-7a5bf456-9088-4861-b817-d04ac71228c8.PNG)

## ToDo
- [x] molecules에 링크 버튼 관련 컴포넌트
- [x] molecules에 image 관련 컴포넌트
- [x] molecules에 여행 요약 정보 관련 컴포넌트
- [x] organisms에 전체 컴포넌트
