### ISSUE TITLE
[FEAT] 그룹 생성 페이지

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/trti_frontend#16]
## 설명
- 그룹 생성 페이지에 필요한 컴포넌트 페이지 구성
![그룹생성페이지](https://user-images.githubusercontent.com/28842641/147060366-a5d1fea5-1ce6-4e68-8e11-30784faf8369.PNG)

## ToDo
- [x] 빈 지도 SVG 추가
- [x] 지도 마크 SVG 추가
- [x] 달력 SVG 추가
- [x] 사람 SVG 추가
- [x] atomic/Label 컴포넌트 추가
- [x] 입력하는 공통 컴포넌트 추가
- [x] 그룹명 입력하는 컴포넌트 추가
- [x] 페이지 구성
