### ISSUE TITLE
[FEAT] TRTI 검사 임시 페이지 

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/trti_frontend#21]
## 설명
- TRTI 검사 임시 페이지 구현하기
- progress bar 만들기

## ToDo
- [x] 체크 모양 SVG 추가
- [x] 질문 컴포넌트 생성
- [x] progress bar 생성
- [x] 캐러셀로 화면 전환
