### ISSUE TITLE
[FEAT] 그룹 결과 페이지

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/trti_frontend#23]
## 설명
- 합의서에 필요한 컴포넌트 구현

## ToDo
- [x] 합의 선택 컴포넌트
![합의 컴포넌트](https://user-images.githubusercontent.com/28842641/147551247-407c9556-303e-4072-bc1c-1ce499b7f46e.png)
- [ ] 합의 박스 컴포넌트
![합의 박스 컴포넌트](https://user-images.githubusercontent.com/28842641/147551323-6387b7c1-8fca-49e0-b6f7-9903053c0996.png)
- [x] 페이지 구성
- [x] 합의서 제목 컴포넌트
- [x] 이미지 + 이름 컴포넌트
