### ISSUE TITLE
[FEAT] 공통 컴포넌트 생성

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/trti_frontend#9]
## 설명
- 모바일 작업을 우선 + 기획 변경으로 인해서 공통 컴포넌트 추가

## ToDo
- [x] 사람 SVG 아이콘 추가
- [x] + SVG 아이콘 추가
- [x] > SVG 아이콘 추가
- [x] 종모양 아이콘 추가
- [x] 마이페이지 아이콘 추가
- [x] 그룹 추가하기 버튼 만들기
- [x] 합의중, 합의완료 컴포넌트 만들기
